package com.imrohansoni.docleaf.core.components

import androidx.annotation.DrawableRes
import androidx.compose.runtime.Immutable
import com.imrohansoni.docleaf.R

@Immutable
class IconResource(@param:DrawableRes val resId: Int)

object Icons {
    val Alert = IconResource(R.drawable.alert)
    val AlignSelection = IconResource(R.drawable.align_selection)
    val Arrow = IconResource(R.drawable.arrow)
    val ArrowAllDirection = IconResource(R.drawable.arrow_all_direction)
    val ArrowDown = IconResource(R.drawable.arrow_down)
    val ArrowLeft = IconResource(R.drawable.arrow_left)
    val ArrowRight = IconResource(R.drawable.arrow_right)
    val Bell = IconResource(R.drawable.bell)
    val Book = IconResource(R.drawable.book)
    val Box = IconResource(R.drawable.box)
    val BoxFill = IconResource(R.drawable.box_fill)
    val Check = IconResource(R.drawable.check)
    val ChevronDown = IconResource(R.drawable.chevron_down)
    val Controller = IconResource(R.drawable.controller)
    val CropPlus = IconResource(R.drawable.copy_plus)
    val Crop = IconResource(R.drawable.crop)
    val Cross = IconResource(R.drawable.cross)
    val Delete = IconResource(R.drawable.delete)
    val Download = IconResource(R.drawable.download)
    val EditText = IconResource(R.drawable.edit_text)
    val File = IconResource(R.drawable.file)
    val Flip = IconResource(R.drawable.flip)
    val Folder = IconResource(R.drawable.folder)
    val FlashlightOn = IconResource(R.drawable.flash)
    val FlashlightOff = IconResource(R.drawable.flash_off)
    val FolderFill = IconResource(R.drawable.folder_fill)
    val Grid = IconResource(R.drawable.grid)
    val Highlighter = IconResource(R.drawable.highlighter)
    val Home = IconResource(R.drawable.home)
    val HomeFill = IconResource(R.drawable.home_fill)
    val IdCard = IconResource(R.drawable.id_card)
    val Image = IconResource(R.drawable.image)
    val Lock = IconResource(R.drawable.lock)
    val MagicWand = IconResource(R.drawable.magic_wand)
    val Mail = IconResource(R.drawable.mail)
    val Pen = IconResource(R.drawable.pen)
    val QrCode = IconResource(R.drawable.qr_code)
    val Redo = IconResource(R.drawable.redo)
    val Rotate = IconResource(R.drawable.rotate)
    val Scan = IconResource(R.drawable.scan)
    val Search = IconResource(R.drawable.search)
    val SecurityWarning = IconResource(R.drawable.security_warning)
    val Settings = IconResource(R.drawable.settings)
    val Signature = IconResource(R.drawable.signature)
    val TextSquare = IconResource(R.drawable.text_square)
    val Undo = IconResource(R.drawable.undo)
    val User = IconResource(R.drawable.user)
    val UserCircle = IconResource(R.drawable.user_circle)
    val UserCircleFill = IconResource(R.drawable.user_circle_fill)
    val UserSquare = IconResource(R.drawable.user_square)
    val Warning = IconResource(R.drawable.warning)
}